/-
Copyright (c) 2026 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael R. Douglas
-/
import ReflectionPositivity.Abstract
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.MeasureTheory.Integral.Pi
import Mathlib.Probability.Distributions.Gaussian.Real

/-!
# Concrete RP instances for product lattice measures

Product Gibbs measures with even ferromagnetic nearest-neighbour
interactions are reflection-positive for the half-space sub-σ-algebra
under any lattice reflection that preserves the bond structure.

## Design & route (2026-07-20)

Full pinned design + proof skeleton: `docs/lattice-rp-design.md` (Gemini-vetted). **Route A**
(measure-theoretic, not the transfer-operator route). The crossing perfect-square core is
**axiom-free** via per-edge Hubbard–Stratonovich (Fubini + 1D Gaussian MGF); landing this
retires pphi2's `gaussian_rp_cov_perfect_square` axiom and discharges pphi2 cylinder OS3 `hRP`.

## Main theorems (planned)

* `MeasureTheory.Measure.isReflectionPositive_of_evenNearestNeighbour` —
  for any finite lattice `Λ` with a measurable reflection `θ : Λ → Λ`
  preserving the edge set, the ferromagnetic Gibbs measure

    `μ ∝ exp(-½ ∑_⟨x,y⟩ J_{x,y} (φ_x - φ_y)² - ∑_x V(φ_x)) ∏_x dφ_x`

  with `J_{x,y} ≥ 0` and `V : ℝ → ℝ` (single-site potential, no parity
  constraint required) is reflection-positive for the half-space
  sub-σ-algebra defined by `θ`. (Glimm-Jaffe Ch. 6 Thm 6.2.2.)

* Specialization to: cylinder `Z_{Nt} × Z_{Ns}` (the asym lattice
  shape for pphi2's cylinder construction), with `θ` = time reflection
  across a time hyperplane and `J_{xy} = 1/a²` for nearest-neighbour
  `⟨xy⟩`. The **`Nt` even** requirement (so the reflection plane sits
  between sites) is reflected here.

* `MeasureTheory.Measure.IsReflectionPositive.weak_limit` — RP is
  closed under characteristic-function-convergent weak limits.
  Generalizes pphi2's existing
  `OSProofs/OS3_RP_Inheritance.rp_closed_under_weak_limit`.

## Interop with pphi2

pphi2 already has the action-decomposition lemma
`OSProofs/OS3_RP_Lattice.action_decomposition` (the `S = S_+ + S_- ∘ θ`
factorization on the asym lattice). After this file lands, the pphi2
RP infrastructure becomes an adapter that proves the asym lattice's
nearest-neighbour interaction satisfies the hypotheses of the
abstract theorem here, and inherits all consequences (CS, chessboard,
transfer-matrix construction) for free.

## References

* Glimm-Jaffe Ch. 6 §6.2 Thm 6.2.2.
* Osterwalder-Seiler (1978) — RP for lattice gauge fields.
* Simon, *P(φ)₂*, §III.

## Status

The Hubbard--Stratonovich edge identity and the finite crossing-edge density
factorization are formalized below for the even, bond-reflection, two-block
case `ι ⊕ ι`.
-/

namespace MeasureTheory.Measure

open MeasureTheory ProbabilityTheory Real

open scoped MeasureTheory ENNReal NNReal BigOperators

noncomputable section

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Configurations for the two-block, bond-reflection lattice `ι ⊕ ι`. -/
abbrev EvenConfig (ι : Type*) := Sum ι ι → ℝ

/-- The positive half of a two-block configuration. -/
def positivePart (φ : EvenConfig ι) : ι → ℝ :=
  fun i => φ (Sum.inl i)

/-- The reflected/negative half of a two-block configuration. -/
def negativePart (φ : EvenConfig ι) : ι → ℝ :=
  fun i => φ (Sum.inr i)

/-- Site reflection swapping the two halves. -/
def evenReflection (ι : Type*) : Sum ι ι ≃ Sum ι ι :=
  Equiv.sumComm ι ι

/-- Field reflection induced by swapping the two lattice halves. -/
def evenTheta (φ : EvenConfig ι) : EvenConfig ι :=
  φ ∘ evenReflection ι

/-- Standard Gaussian product measure for the HS auxiliary field. -/
def stdGaussianPi (ι : Type*) [Fintype ι] : Measure (ι → ℝ) :=
  Measure.pi (fun _ : ι => ProbabilityTheory.gaussianReal 0 (1 : ℝ≥0))

/-- Data for the generic even nearest-neighbour ferromagnetic two-block density.

`EPos` is the half action. The crossing family is encoded by `edges` and
nonnegative couplings `J` on those edges.
-/
structure EvenFerroReflectionData (ι : Type*) [Fintype ι] [DecidableEq ι] where
  EPos : (ι → ℝ) → ℝ
  edges : Finset ι
  J : ι → ℝ
  hJ : ∀ i, i ∈ edges → 0 ≤ J i

namespace EvenFerroReflectionData

variable (d : EvenFerroReflectionData ι)

/-- Product Lebesgue reference measure on the full two-block configuration space. -/
def baseMeasure (_d : EvenFerroReflectionData ι) : Measure (EvenConfig ι) :=
  Measure.pi (fun _ : Sum ι ι => (volume : Measure ℝ))

/-- The positive-half σ-algebra generated by `φ ↦ φ ∘ inl`. -/
@[reducible]
def mPos (_d : EvenFerroReflectionData ι) : MeasurableSpace (EvenConfig ι) :=
  MeasurableSpace.comap positivePart inferInstance

/-- Crossing energy `Σ_i J_i a_i b_i`. -/
def crossingEnergy (a b : ι → ℝ) : ℝ :=
  ∑ i ∈ d.edges, d.J i * a i * b i

/-- Unnormalised Gibbs density against `baseMeasure`. -/
def density (φ : EvenConfig ι) : ℝ :=
  Real.exp (-d.EPos (positivePart φ) - d.EPos (negativePart φ) +
    d.crossingEnergy (positivePart φ) (negativePart φ))

/-- The corresponding unnormalised Gibbs measure. -/
def μ : Measure (EvenConfig ι) :=
  d.baseMeasure.withDensity fun φ => ENNReal.ofReal (d.density φ)

/-- The reflection map on configurations. -/
def θ (_d : EvenFerroReflectionData ι) : EvenConfig ι → EvenConfig ι :=
  evenTheta

end EvenFerroReflectionData

/-- One half of a Hubbard--Stratonovich crossing-edge factor. -/
def hsHalfFactor (edges : Finset ι) (J : ι → ℝ) (i : ι) (a : ι → ℝ) (z : ℝ) : ℝ :=
  if i ∈ edges then
    Real.exp (-(J i / 2 * a i ^ 2) + Real.sqrt (J i) * z * a i)
  else
    1

/-- The product of the two half HS factors for one crossing coordinate. -/
def hsEdgeFactor (edges : Finset ι) (J : ι → ℝ) (i : ι) (a b : ι → ℝ) (z : ℝ) : ℝ :=
  hsHalfFactor edges J i a z * hsHalfFactor edges J i b z

namespace EvenFerroReflectionData

variable (d : EvenFerroReflectionData ι)

/-- The positive-half integrand appearing after HS factorization. -/
def posPartIntegrand (a : ι → ℝ) (z : ι → ℝ) : ℝ :=
  Real.exp (-d.EPos a) * ∏ i, hsHalfFactor d.edges d.J i a (z i)

end EvenFerroReflectionData

/-- Per-edge Hubbard--Stratonovich identity in the self-term form.

This is the direct standard-normal MGF identity at
`t = sqrt J * (a + b)`.
-/
theorem hs_edge (J a b : ℝ) (hJ : 0 ≤ J) :
    Real.exp (J / 2 * a ^ 2) * Real.exp (J / 2 * b ^ 2) * Real.exp (J * a * b)
      =
        ∫ z : ℝ, Real.exp (Real.sqrt J * z * a) * Real.exp (Real.sqrt J * z * b)
          ∂(ProbabilityTheory.gaussianReal 0 (1 : ℝ≥0)) := by
  have hmgf :=
    congr_fun
      (ProbabilityTheory.mgf_id_gaussianReal (μ := (0 : ℝ)) (v := (1 : ℝ≥0)))
      (Real.sqrt J * (a + b))
  dsimp [ProbabilityTheory.mgf] at hmgf
  have hprod :
      (fun z : ℝ => Real.exp (Real.sqrt J * z * a) *
        Real.exp (Real.sqrt J * z * b))
        = fun z : ℝ => Real.exp ((Real.sqrt J * (a + b)) * z) := by
    funext z
    rw [← Real.exp_add]
    congr 1
    ring
  rw [hprod, hmgf]
  have hsqrt : Real.sqrt J ^ 2 = J := Real.sq_sqrt hJ
  rw [← Real.exp_add, ← Real.exp_add]
  congr 1
  calc
    J / 2 * a ^ 2 + J / 2 * b ^ 2 + J * a * b = J * (a + b) ^ 2 / 2 := by
      ring
    _ = 0 * (Real.sqrt J * (a + b)) + 1 * (Real.sqrt J * (a + b)) ^ 2 / 2 := by
      rw [mul_pow, hsqrt]
      ring

/-- Per-edge HS identity solved for the bare crossing factor `exp (Jab)`.

The compensating self terms are moved into the two half factors.
-/
theorem hs_edge_cross (J a b : ℝ) (hJ : 0 ≤ J) :
    Real.exp (J * a * b)
      =
        ∫ z : ℝ,
          Real.exp (-(J / 2 * a ^ 2) + Real.sqrt J * z * a) *
            Real.exp (-(J / 2 * b ^ 2) + Real.sqrt J * z * b)
          ∂(ProbabilityTheory.gaussianReal 0 (1 : ℝ≥0)) := by
  have hmgf :=
    congr_fun
      (ProbabilityTheory.mgf_id_gaussianReal (μ := (0 : ℝ)) (v := (1 : ℝ≥0)))
      (Real.sqrt J * (a + b))
  dsimp [ProbabilityTheory.mgf] at hmgf
  have hfun :
      (fun z : ℝ =>
        Real.exp (-(J / 2 * a ^ 2) + Real.sqrt J * z * a) *
          Real.exp (-(J / 2 * b ^ 2) + Real.sqrt J * z * b))
        =
          fun z : ℝ => Real.exp (-(J / 2 * a ^ 2) - (J / 2 * b ^ 2)) *
            Real.exp ((Real.sqrt J * (a + b)) * z) := by
    funext z
    rw [← Real.exp_add]
    rw [← Real.exp_add]
    congr 1
    ring
  rw [hfun]
  rw [integral_const_mul]
  rw [hmgf]
  rw [← Real.exp_add]
  congr 1
  have hsqrt : Real.sqrt J ^ 2 = J := Real.sq_sqrt hJ
  calc
    J * a * b = -(J / 2 * a ^ 2) - (J / 2 * b ^ 2) +
        (0 * (Real.sqrt J * (a + b)) + 1 * (Real.sqrt J * (a + b)) ^ 2 / 2) := by
      rw [mul_pow, hsqrt]
      ring

/-- Finite product HS identity for all crossing edges. -/
theorem hs_edges (d : EvenFerroReflectionData ι) (a b : ι → ℝ) :
    Real.exp (d.crossingEnergy a b)
      =
        ∫ z : ι → ℝ, ∏ i, hsEdgeFactor d.edges d.J i a b (z i)
          ∂(stdGaussianPi ι) := by
  rw [EvenFerroReflectionData.crossingEnergy]
  rw [stdGaussianPi, integral_fintype_prod_eq_prod]
  have hint : ∀ i : ι,
      (∫ x : ℝ, hsEdgeFactor d.edges d.J i a b x
          ∂ProbabilityTheory.gaussianReal 0 (1 : ℝ≥0))
        = if i ∈ d.edges then Real.exp (d.J i * a i * b i) else 1 := by
    intro i
    by_cases hi : i ∈ d.edges
    · simp [hsEdgeFactor, hsHalfFactor, hi,
        (hs_edge_cross (d.J i) (a i) (b i) (d.hJ i hi)).symm]
    · simp [hsEdgeFactor, hsHalfFactor, hi]
  simp_rw [hint]
  rw [Finset.prod_ite_mem]
  simpa [Finset.univ_inter] using
    Real.exp_sum d.edges (fun i => d.J i * a i * b i)

/-- HS factorization of the unnormalised two-block Gibbs density. -/
theorem density_hs_factor (d : EvenFerroReflectionData ι) (φ : EvenConfig ι) :
    d.density φ
      =
        ∫ z : ι → ℝ,
          d.posPartIntegrand (positivePart φ) z *
            d.posPartIntegrand (negativePart φ) z
          ∂(stdGaussianPi ι) := by
  let a := positivePart φ
  let b := negativePart φ
  have hfun :
      (fun z : ι → ℝ => d.posPartIntegrand a z * d.posPartIntegrand b z)
        =
          fun z : ι → ℝ => Real.exp (-d.EPos a - d.EPos b) *
            ∏ i, hsEdgeFactor d.edges d.J i a b (z i) := by
    funext z
    rw [EvenFerroReflectionData.posPartIntegrand, EvenFerroReflectionData.posPartIntegrand]
    simp only [hsEdgeFactor]
    rw [Finset.prod_mul_distrib]
    have hExp : Real.exp (-d.EPos a) * Real.exp (-d.EPos b) =
        Real.exp (-d.EPos a - d.EPos b) := by
      rw [← Real.exp_add]
      ring_nf
    rw [← hExp]
    ring_nf
  rw [EvenFerroReflectionData.density]
  change Real.exp (-d.EPos a - d.EPos b + d.crossingEnergy a b) = _
  rw [hfun]
  rw [integral_const_mul]
  rw [← hs_edges d a b]
  rw [← Real.exp_add]

/-- Reflection positivity from the square representation produced by the HS/block split.

The remaining measure-theoretic assembly for the full GJ 6.2.2 theorem is exactly the
`h_square` hypothesis: for every positive-half observable, the reflection form must
be rewritten as an integral of a pointwise square over the HS Gaussian field.
-/
theorem isReflectionPositive_of_evenNearestNeighbour (d : EvenFerroReflectionData ι)
    (h_square : ∀ F : EvenConfig ι → ℝ, Measurable[d.mPos] F →
      Integrable (fun x => F x * F (d.θ x)) d.μ →
        ∃ I : (ι → ℝ) → ℝ,
          reflectionInnerProduct d.μ d.θ F F =
            ∫ z : ι → ℝ, (I z) ^ 2 ∂stdGaussianPi ι) :
    IsReflectionPositive d.μ d.θ d.mPos := by
  intro F hF hInt
  rcases h_square F hF hInt with ⟨I, hI⟩
  rw [hI]
  exact integral_nonneg fun z => sq_nonneg (I z)

/-- Reflection positivity is closed under convergence of the reflection forms.

This is the abstract weak-limit closure needed downstream: if every approximating
measure is RP and, for each admissible `F`, the corresponding reflection forms
converge to the limiting reflection form, then the limit is RP.
-/
theorem IsReflectionPositive.weak_limit {Ω : Type*} [m0 : MeasurableSpace Ω]
    {μ : Measure Ω} {μn : ℕ → Measure Ω} {θ : Ω → Ω}
    {mPos : MeasurableSpace Ω}
    (hRP : ∀ n, @IsReflectionPositive Ω m0 (μn n) θ mPos)
    (hconv : ∀ F : Ω → ℝ, Measurable[mPos] F →
      Integrable (fun x => F x * F (θ x)) μ →
        (∀ n, Integrable (fun x => F x * F (θ x)) (μn n)) ∧
          Filter.Tendsto
            (fun n => @reflectionInnerProduct Ω m0 (μn n) θ F F)
            Filter.atTop
            (nhds (@reflectionInnerProduct Ω m0 μ θ F F))) :
    @IsReflectionPositive Ω m0 μ θ mPos := by
  intro F hF hInt
  rcases hconv F hF hInt with ⟨hIntn, hlim⟩
  exact ge_of_tendsto hlim (.of_forall fun n => hRP n F hF (hIntn n))

end

end MeasureTheory.Measure
